,hkgckhgc ljgcvlujch
ljugclgvluujyhvlvyv
pujhv ikhvkjbkjblgb
ojhycvoujh lujuhvluyv

utjdcfvlujyvlyyhv;iyg
khcvlujgcvlujvujufvjv
p;juvhlujhiugikugujug
yiyhvikgiugugougiugikg

likgchvlihfviv;
p;ujvh;upyvuyv